---
id: matsuerubykaigi05
base_name: chef_cookbooks
tags:
- chef
- provisioning
presentation_date: 2014-03-15
version: 2014.03.15.0
licenses:
- CC BY-SA 2.1 JP
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Yuya.Nishida.
  email: yuyaAT@ATj96DOT.DOTorg
  rubygems_user: nishidayuya
  slideshare_user: 
  speaker_deck_user: nishidayuya
